services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://backend.ii-agent.ignitabull.org}
      - NEXT_PUBLIC_VSCODE_URL=${NEXT_PUBLIC_VSCODE_URL:-http://127.0.0.1:8080}
    volumes:
      - workspace:/app/workspace
    depends_on:
      - backend
    labels:
      - "coolify.managed=true"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    init: true
    expose:
      - "8000"
    env_file: 
      - .env
    environment:
      # Application Configuration
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - STATIC_FILE_BASE_URL=${STATIC_FILE_BASE_URL:-https://backend.ii-agent.ignitabull.org/}
      - WORKSPACE_PATH=/app/workspace
    volumes:
      - workspace:/app/workspace
    labels:
      - "coolify.managed=true"

volumes:
  workspace:
