services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://backend.ii-agent.ignitabull.org}
      - NEXT_PUBLIC_VSCODE_URL=${NEXT_PUBLIC_VSCODE_URL:-http://127.0.0.1:8080}
    volumes:
      - ${WORKSPACE_PATH:-../workspace}:/app/workspace
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    init: true
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file: 
      - ../.env
    environment:
      # Application Configuration
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - STATIC_FILE_BASE_URL=${STATIC_FILE_BASE_URL:-https://backend.ii-agent.ignitabull.org/}
      - WORKSPACE_PATH=${WORKSPACE_PATH}
    volumes:
      - ${WORKSPACE_PATH:-../workspace}:/app/workspace

volumes:
  workspace:
